name: 'Terraform_Deploy'
on:
  push:
    branches:
      - main
jobs:
  terraform:
    name: 'terraform'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: list files in directory
      run: |
       ls -R ./
    - name: Current Working Directory
      run: |
        pwd
    - name: Terraform Init
      uses: hashicorp/terraform-github-actions/@main
      with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: '.'
       
