name: 'Terraform_Deploy'
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
jobs:
  terraform:
    name: 'terraform'
    runs-on: ubuntu-latest
    env:
      ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      ARM_TENANT_ID: "${{ secrets.AZURE_AD_TENANT_ID  }}"
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.KEY }}
    - name: list files in directory
      run: |
       ls -R ./
    - name: Current Working Directory
      run: |
        pwd
    - name: test secrets
      run: |
        echo "Sub: ${{ secrets.AZURE_SUBSCRIPTION_ID }}"
        echo "Tenant: ${{ secrets.AZURE_AD_TENANT_ID }}"
        echo "Key: ${{ secrets.KEY }}"
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: '{"subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_AD_TENANT_ID }}"}' 
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
          azcliversion: latest
          inlineScript: |
            az account show
    - name: Terraform Init
      uses: hashicorp/terraform-github-actions/@master
      with:
          tf_actions_version: 1.5.7
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: '.'
          tf_actions_comment: true
    # - name: Terraform Plan
    #   uses: hashicorp/terraform-github-actions/@master
    #   with:
    #       tf_actions_version: 1.5.7
    #       tf_actions_subcommand: 'plan'
    #       tf_actions_working_dir: '.'