name: 'Terraform_Deploy'
on:
  push:
    branches:
      - main
jobs:
  terraform:
    name: 'terraform'
    runs-on: ubuntu-latest
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID  }}
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: list files in directory
      run: |
       ls -R ./
    - name: Current Working Directory
      run: |
        pwd
    - name: Terraform Init
      uses: hashicorp/terraform-github-actions/@master
      with:
          tf_actions_version: 1.5.5
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: '.'
    - name: Terraform Plan
      uses: hashicorp/terraform-github-actions/@master
      with:
          tf_actions_version: 1.5.5
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: '.'
       
